//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.WCFIsDead.WCF.Client.CalculatorClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calculation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Calculation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal Operand1Field;
        
        private decimal Operand2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpertorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Operand1 {
            get {
                return this.Operand1Field;
            }
            set {
                if ((this.Operand1Field.Equals(value) != true)) {
                    this.Operand1Field = value;
                    this.RaisePropertyChanged("Operand1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Operand2 {
            get {
                return this.Operand2Field;
            }
            set {
                if ((this.Operand2Field.Equals(value) != true)) {
                    this.Operand2Field = value;
                    this.RaisePropertyChanged("Operand2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Opertor {
            get {
                return this.OpertorField;
            }
            set {
                if ((object.ReferenceEquals(this.OpertorField, value) != true)) {
                    this.OpertorField = value;
                    this.RaisePropertyChanged("Opertor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CalculationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation CalculationField;
        
        private decimal ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation Calculation {
            get {
                return this.CalculationField;
            }
            set {
                if ((object.ReferenceEquals(this.CalculationField, value) != true)) {
                    this.CalculationField = value;
                    this.RaisePropertyChanged("Calculation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorClient.ICalculatorService")]
    public interface ICalculatorService {
        
        // CODEGEN: Generating message contract since element name calculation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/Execute", ReplyAction="*")]
        Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse Execute(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse> ExecuteAsync(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://tempuri.org/", Order=0)]
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation calculation;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation calculation) {
            this.calculation = calculation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.CalculationResult ExecuteResult;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(Lab.WCFIsDead.WCF.Client.CalculatorClient.CalculationResult ExecuteResult) {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService>, Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService.Execute(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Lab.WCFIsDead.WCF.Client.CalculatorClient.CalculationResult Execute(Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation calculation) {
            Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest inValue = new Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest();
            inValue.Body = new Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequestBody();
            inValue.Body.calculation = calculation;
            Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse retVal = ((Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService)(this)).Execute(inValue);
            return retVal.Body.ExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse> Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService.ExecuteAsync(Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteResponse> ExecuteAsync(Lab.WCFIsDead.WCF.Client.CalculatorClient.Calculation calculation) {
            Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest inValue = new Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequest();
            inValue.Body = new Lab.WCFIsDead.WCF.Client.CalculatorClient.ExecuteRequestBody();
            inValue.Body.calculation = calculation;
            return ((Lab.WCFIsDead.WCF.Client.CalculatorClient.ICalculatorService)(this)).ExecuteAsync(inValue);
        }
    }
}
